---
title: "phos_F_longterm"
format: html
---

# Load dependencies
```{r setup}
#| message: false
#| warning: false

source(here::here("R/library.R"))
source(here::here("R/functions.R"))
load(here::here("data/phos_F_renamed2_longterm.rda"))
load(here::here("data/metadata_F_longterm.rda"))
load(here::here("data/phos_F_renamed2_longterm_filt_norm_batchcorr.rda"))
load(here::here("data/phos_F_renamed2_longterm_filt_norm.rda"))
```

# VV1
```{r}
# valid values
valid_counts <- colSums(!is.na(phos_F_renamed2_longterm))
count_data <- data.frame(column = names(valid_counts), count = valid_counts)
count_data$column <- factor(count_data$column, levels = count_data$column)


mean_value <- mean(count_data$count)
y_max <- max(count_data$count)
y_buffer <- max(20, 0.05 * y_max)
y_limit <- y_max + y_buffer

vv1 <- ggplot(count_data, aes(x = column, y = count)) +
  geom_bar(stat = "identity", fill = "lightblue") +
  geom_hline(yintercept = mean_value, color = "red", linetype = "dashed", size = 1, alpha = 0.3) +
  annotate("text", x = length(count_data$column) / 2 + 0.5, 
           y = mean_value + y_buffer / 2,
           label = paste0("Mean = ", round(mean_value, 0)),
           color = "red", size = 5, fontface = "bold") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)), limits = c(0, y_limit)) +
  labs(
    title = "Phosphosites per sample, female: longterm study (n=50)",
    x = "",
    y = "Valid Values") +
  theme_minimal(base_size = 14) +
  theme(plot.title   = element_text(face = "bold", hjust = 0.5, size = 13),
        axis.text.x  = element_text(angle = 45, hjust = 1, vjust = 1, size = 8, color = "black"),
        axis.text.y  = element_text(size = 12, color = "black"),
        axis.title.x = element_text(size = 14, color = "black"),
        axis.title.y = element_text(size = 14, color = "black"),
        panel.grid.major.x = element_blank())


print(vv1)
ggsave(file.path("doc", "vv1_female_prot_longterm.png"), plot = vv1, width = 7, height = 3, dpi = 300, bg = "white")
```
# Distribution
```{r}
## Distribution
# Now, create the plot and save it
png(filename = "doc/boxplot_phos_female_longterm.png",
    width    = 10,
    height   = 6,
    units    = "in",
    res      = 300)

# 1. Draw the boxplot as before
boxplot(phos_F_renamed2_longterm, 
        main = "Male longterm study (n=50), phospho",
        ylab = "Log2 Intensity",
        col = "lightblue")

dev.off()

##########
# Convert data to long format
df_long <- tidyr::pivot_longer(phos_F_renamed2_longterm, 
                               cols = everything(), 
                               names_to = "sample_id", 
                               values_to = "intensity")

density_plot <- ggplot(df_long, aes(x = intensity, color = sample_id)) +
  geom_density() +
  labs(title = "Density Distribution, female:longterm (phospho)", x = "Intensity", y = "Density") +
  theme_minimal(base_size = 14) +
  theme(
      plot.title = element_text(hjust = 0.5, face = "bold", size = 13),
      legend.position = "none")

density_plot
ggsave(file.path("doc", "densityplot_F_phospho_longterm.png"),
       plot = density_plot, width = 7, height = 4, dpi = 300, bg = "white")

```

```{r}
# Filter on total matrix (longterm)
phos_F_renamed2_longterm_filt100 <- PhosR::selectOverallPercent(phos_F_renamed2_longterm, 1.0)   #3821
phos_F_renamed2_longterm_filt70  <- PhosR::selectOverallPercent(phos_F_renamed2_longterm, 0.70)  #10622
phos_F_renamed2_longterm_filt50  <- PhosR::selectOverallPercent(phos_F_renamed2_longterm, 0.50)  #14413

phos_F_renamed2_longterm_filt <- phos_F_renamed2_longterm_filt50

usethis::use_data(phos_F_renamed2_longterm_filt, overwrite = TRUE)

```
## VV2
```{r}
# valid values
valid_counts <- colSums(!is.na(phos_F_renamed2_longterm_filt))
count_data <- data.frame(column = names(valid_counts), count = valid_counts)
count_data$column <- factor(count_data$column, levels = count_data$column)

mean_value <- mean(count_data$count)
y_max <- max(count_data$count)
y_buffer <- max(20, 0.05 * y_max)
y_limit <- y_max + y_buffer

vv2 <- ggplot(count_data, aes(x = column, y = count)) +
  geom_bar(stat = "identity", fill = "lightblue") +
  geom_hline(yintercept = mean_value, color = "red", linetype = "dashed", size = 1, alpha = 0.3) +
  annotate("text",
           x = length(count_data$column) / 2 + 0.5,
           y = mean_value + y_buffer / 2,
           label = paste0("Mean = ", round(mean_value, 0)),
           color = "red", size = 5, fontface = "bold") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)), limits = c(0, y_limit)) +
  labs(
    title = "Phosphosites per sample, female-longterm (n=50)",
    x = "",
    y = "Valid Values"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title   = element_text(face = "bold", hjust = 0.5, size = 13),
    axis.text.x  = element_text(angle = 45, hjust = 1, vjust = 1, size = 8, color = "black"),
    axis.text.y  = element_text(size = 12, color = "black"),
    axis.title.x = element_text(size = 14, color = "black"),
    axis.title.y = element_text(size = 14, color = "black"),
    panel.grid.major.x = element_blank()
  )

print(vv2)
ggsave(file.path("doc", "vv2_female_phospho_longterm.png"),
       plot = vv2, width = 7, height = 3, dpi = 300, bg = "white")

```

# Normalize
```{r}
# from PhosR package — longterm
phos_F_renamed2_longterm_filt_norm <- medianScaling(
  phos_F_renamed2_longterm_filt[1:ncol(phos_F_renamed2_longterm_filt)],
  scale = TRUE
)
phos_F_renamed2_longterm_filt_norm <- as.data.frame(phos_F_renamed2_longterm_filt)

usethis::use_data(phos_F_renamed2_longterm_filt_norm, overwrite = TRUE)

```



# Distribution
```{r}


# Now, create the plot and save it
png(filename = "doc/boxplot_phos_female_renamed_longterm_filt_norm.png",
    width    = 10,
    height   = 6,
    units    = "in",
    res      = 300)

# 1. Draw the boxplot as before
boxplot(prot_F_renamed_longterm_filt_norm, 
        main = "Female longterm (n=50), phospho",
        ylab = "Log2 Intensity",
        col = "lightblue")

dev.off()

####
# Convert data to long format
df_long <- tidyr::pivot_longer(phos_F_renamed2_longterm_filt_norm, 
                               cols = everything(), 
                               names_to = "sample_id", 
                               values_to = "intensity")

density_plot_global <- ggplot(df_long, aes(x = intensity, color = sample_id)) +
  geom_density() +
  labs(title = "Density Distribution, female:longterm (phospho), norm", x = "Intensity", y = "Density") +
  theme_minimal(base_size = 14) +
  theme(
      plot.title = element_text(hjust = 0.5, face = "bold", size = 13),
      legend.position = "none")

density_plot_global
ggsave(file.path("doc", "densityplot_phospho_F_longterm_norm.png"),
       plot = density_plot_global, width = 7, height = 4, dpi = 300, bg = "white")

```


```{r}
# PCA3
n_original <- nrow(phos_F_renamed2_longterm_filt_norm) 
df_nona <- na.omit(phos_F_renamed2_longterm_filt_norm) 
n_nona <- nrow(df_nona)

# transpose data 
pca_nona <- prcomp(t(df_nona), scale = TRUE)
# quick scatter plot
factoextra::fviz_pca_ind(pca_nona) 
plot(pca_nona$x[,1], pca_nona$x[,2])

# Eigenvalues (variance explained by each PC)
pca_var <- pca_nona$sdev^2 
pca_var_perc <- round(pca_var/sum(pca_var)*100, digits = 1)
fviz_eig(pca_nona, addlabels = TRUE)  # scree plot 

pca_results <- as.data.frame(pca_nona$x) %>%
  tibble::rownames_to_column("new_sample_id")  # keep sample IDs

pca_data <- pca_results %>%
  dplyr::select(new_sample_id, PC1, PC2, PC3, PC4) %>% 
  dplyr::inner_join(metadata_F_longterm, by = "new_sample_id") %>%   # (left as-is)
  dplyr::mutate(
    hover_text = paste0(
      "new_sample_id: ", new_sample_id,
      "<br>Sample: ", sample_id,
      "<br>Diet: ", diet,
      "<br>Strain: ", strain
    )
  )

# Should be all TRUE / empty set
all(pca_results$sample_id %in% metadata_F_longterm$new_sample_id)

pca_day_norm <- plot_pca(
    data = pca_data,
    color_var = "prep_day_batch",
    shape_var = "strain",
    palette_name = "Set1",
    plot_title = "phospho, F, longterm (n=50)",
    ellipse = TRUE
)

pca_beatbox_norm <- plot_pca(
    data = pca_data,
    color_var = "prep_day_batch",
    shape_var = "beatbox_batch",
    shape_vals = c(16,17,15,3,7,8,1,2,0,4,5,6),
    palette_name = "Set1",
    plot_title = "phospho, F, longterm (n=50)",
    ellipse = FALSE
)

pca_strain_norm <- plot_pca(
    data = pca_data,
    color_var = "strain",
    shape_var = "weeks",
    color_vals = c("Ntac" = "#AA3377", "J" = "#CCBB44"),
    plot_title = "phospho, F, longterm (n=50)",
    ellipse = TRUE
)

pca_weeks_norm <- plot_pca(
    data = pca_data,
    color_var = "weeks",
    shape_var = "strain",
    palette_name = "Dark2",
    plot_title = "phospho, F, longterm (n=50)",
    ellipse = TRUE
)

#####################
pca_strain_norm_pc23 <- ggplot(pca_data, aes(x = PC2, y = PC3, color = strain, text = hover_text)) +
  geom_point(size = 3.5, alpha = 0.7) +
  stat_ellipse(aes(group = strain, fill = strain), geom = "path", show.legend = FALSE) +
  scale_color_manual(values = c("Ntac" = "#AA3377", "J" = "#CCBB44" )) +
  labs(
    title = "phospho, F, longterm (n=50)",
    x = paste0("PC2 (", pca_var_perc[2], "%)"),
    y = paste0("PC3 (", pca_var_perc[3], "%)")
  ) +
  theme_bw(base_size = 14) +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5)
  )

pca_strain_norm_pc13 <- ggplot(pca_data, aes(x = PC1, y = PC3, color = strain, text = hover_text)) +
  geom_point(size = 3.5, alpha = 0.7) +
  stat_ellipse(aes(group = strain, fill = strain), geom = "path", show.legend = FALSE) +
  scale_color_manual(values = c("Ntac" = "#AA3377", "J" = "#CCBB44" )) +
  labs(
    title = "phospho, F, longterm (n=50)",
    x = paste0("PC1 (", pca_var_perc[1], "%)"),
    y = paste0("PC3 (", pca_var_perc[3], "%)")
  ) +
  theme_bw(base_size = 14) +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5)
  )

print(pca_strain_norm_pc23)
print(pca_strain_norm_pc13)

ggsave(file.path("doc", "pca_day_norm_Flong_norm.png"),      plot = pca_day_norm,      width = 7, height = 5, dpi = 300, bg = "white")
ggsave(file.path("doc", "pca_beatbox_norm_Flong_norm.png"),  plot = pca_beatbox_norm,  width = 7, height = 5, dpi = 300, bg = "white")
ggsave(file.path("doc", "pca_strain_norm_Flong_norm.png"),   plot = pca_strain_norm,   width = 7, height = 5, dpi = 300, bg = "white")
ggsave(file.path("doc", "pca_weeks_norm_Flong_norm.png"),    plot = pca_weeks_norm,    width = 7, height = 5, dpi = 300, bg = "white")
ggsave(file.path("doc", "pca_strain23_norm_Flong_norm.png"), plot = pca_strain_norm_pc23, width = 7, height = 5, dpi = 300, bg = "white")
ggsave(file.path("doc", "pca_strain13_norm_Flong_norm.png"), plot = pca_strain_norm_pc13, width = 7, height = 5, dpi = 300, bg = "white")

```
# Batchcorr
```{r}
setequal(colnames(phos_F_renamed2_longterm_filt_norm), metadata_F_longterm$new_sample_id) # TRUE
all(colnames(phos_F_renamed2_longterm_filt_norm) == metadata_F_longterm$new_sample_id)    # TRUE

phos_F_renamed2_longterm_filt_norm_batchcorr <- limma::removeBatchEffect(
  phos_F_renamed2_longterm_filt_norm,
  batch = metadata_F_longterm$beatbox_batch
)
phos_F_renamed2_longterm_filt_norm_batchcorr <- as.data.frame(phos_F_renamed2_longterm_filt_norm_batchcorr)

usethis::use_data(phos_F_renamed2_longterm_filt_norm_batchcorr, overwrite = TRUE)

```
# PCA3
```{r}
n_original <- nrow(phos_F_renamed2_longterm_filt_norm_batchcorr) # 7565
df_nona <- na.omit(phos_F_renamed2_longterm_filt_norm_batchcorr) # 6287
n_nona <- nrow(df_nona)

# transpose data 
pca_nona <- prcomp(t(df_nona), scale = TRUE)
# quick scatter plot
factoextra::fviz_pca_ind(pca_nona) 
plot(pca_nona$x[,1], pca_nona$x[,2])

# Eigenvalues (variance explained by each PC)
pca_var <- pca_nona$sdev^2 
pca_var_perc <- round(pca_var/sum(pca_var)*100, digits = 1)
fviz_eig(pca_nona, addlabels = TRUE)  # scree plot 

pca_results <- as.data.frame(pca_nona$x) %>%
  tibble::rownames_to_column("new_sample_id")  # keep sample IDs

pca_data <- pca_results %>%
  dplyr::select(new_sample_id, PC1, PC2, PC3, PC4) %>% 
  dplyr::inner_join(metadata_F_longterm, by = "new_sample_id") %>%
  dplyr::mutate(
    hover_text = paste0(
      "new_sample_id: ", new_sample_id,
      "<br>Sample: ", sample_id,
      "<br>Diet: ", diet,
      "<br>Strain: ", strain
    )
  )

# Should be all TRUE / empty set
all(pca_results$sample_id %in% metadata_F_longterm$new_sample_id)

pca_day_batchcorr <- plot_pca(
    data = pca_data,
    color_var = "prep_day_batch",
    shape_var = "strain",
    palette_name = "Set1",
    plot_title = "phospho, F, longterm (n=50)",
    ellipse = TRUE
)

pca_beatbox_batchcorr <- plot_pca(
    data = pca_data,
    color_var = "prep_day_batch",
    shape_var = "beatbox_batch",
    shape_vals = c(16,17,15,3,7,8,1,2,0,4,5,6),
    palette_name = "Set1",
    plot_title = "phospho, F, longterm (n=50)",
    ellipse = FALSE
)

pca_weeks_batchcorr <- plot_pca(
    data = pca_data,
    color_var = "weeks",
    shape_var = "strain",
    palette_name = "Dark2",
    plot_title = "phospho, F, longterm (n=50)",
    ellipse = TRUE
)

pca_strain_batchcorr <- plot_pca(
    data = pca_data,
    color_var = "strain",
    shape_var = "weeks",
    color_vals = c("Ntac" = "#AA3377", "J" = "#CCBB44"),
    plot_title = "phospho, F, longterm (n=50)",
    ellipse = TRUE
)

#####################
pca_strain_batchcorr_pc23 <- ggplot(pca_data, aes(x = PC2, y = PC3, color = strain, shape = diet, text = hover_text)) +
  geom_point(size = 3.5, alpha = 0.7) +
  stat_ellipse(aes(group = strain, fill = strain), geom = "path", show.legend = FALSE) +
  scale_color_manual(values = c("Ntac" = "#AA3377", "J" = "#CCBB44" )) +
  labs(
    title = "phospho, F, longterm (n=50)",
    #subtitle = paste("based on", n_nona, "proteins out of", n_original),
    x = paste0("PC2 (", pca_var_perc[2], "%)"),
    y = paste0("PC3 (", pca_var_perc[3], "%)")
  ) +
  theme_bw(base_size = 14) +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5)
  )

pca_strain_batchcorr_pc13 <- ggplot(pca_data, aes(x = PC1, y = PC3, color = strain, shape = diet, text = hover_text)) +
  geom_point(size = 3.5, alpha = 0.7) +
  stat_ellipse(aes(group = strain, fill = strain), geom = "path", show.legend = FALSE) +
  scale_color_manual(values = c("Ntac" = "#AA3377", "J" = "#CCBB44" )) +
  labs(
    title = "phospho, F, longterm (n=50)",
    #subtitle = paste("based on", n_nona, "proteins out of", n_original),
    x = paste0("PC1 (", pca_var_perc[1], "%)"),
    y = paste0("PC3 (", pca_var_perc[3], "%)")
  ) +
  theme_bw(base_size = 14) +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5)
  )

print(pca_strain_batchcorr_pc23)
print(pca_strain_batchcorr_pc13)

ggsave(file.path("doc", "pca_day_Flong_norm_batchcorr.png"),     plot = pca_day_batchcorr,     width = 7, height = 5, dpi = 300, bg = "white")
ggsave(file.path("doc", "pca_beatbox_Flong_norm_batchcorr.png"), plot = pca_beatbox_batchcorr,  width = 7, height = 5, dpi = 300, bg = "white")
ggsave(file.path("doc", "pca_weeks_Flong_norm_batchcorr.png"),   plot = pca_weeks_batchcorr,    width = 7, height = 5, dpi = 300, bg = "white")
ggsave(file.path("doc", "pca_strain_Flong_norm_batchcorr.png"),  plot = pca_strain_batchcorr,   width = 7, height = 5, dpi = 300, bg = "white")
ggsave(file.path("doc", "pca_strain23_Flong_norm_batchcorr.png"), plot = pca_strain_batchcorr_pc23, width = 7, height = 5, dpi = 300, bg = "white")
ggsave(file.path("doc", "pca_strain13_Flong_norm_batchcorr.png"), plot = pca_strain_batchcorr_pc13, width = 7, height = 5, dpi = 300, bg = "white")

```
# Limma: batchcorr data
```{r}
class(metadata_F_longterm$weeks)
levels(metadata_F_longterm$weeks)

metadata_F_longterm$weeks <- factor(metadata_F_longterm$weeks, levels = c("24", "36", "48"))
metadata_F_longterm$strain<- factor(metadata_F_longterm$strain, levels = c("J", "Ntac"))
metadata_F_longterm$Combined <-
  with(metadata_F_longterm, factor(paste0("w", weeks, "_", strain)))

class(metadata_F_longterm$Combined)
levels(metadata_F_longterm$Combined)

design_batchcorr <- model.matrix(~0 + Combined, data = metadata_F_longterm)
colnames(design_batchcorr) <- sub("Combined", "", colnames(design_batchcorr))
colnames(design_batchcorr)

contrasts_batchcorr <- makeContrasts(
  main_w24_w36 = ((w36_J + w36_Ntac)/2) - ((w24_J + w24_Ntac)/2), 
  main_w36_w48 = ((w48_J + w36_Ntac)/2) - ((w48_J + w36_Ntac)/2),
  main_w24_w38 = ((w48_J + w24_Ntac)/2) - ((w48_J + w24_Ntac)/2),
  
  J_w24_w36    = w36_J    - w24_J,
  Ntac_w24_w36 = w36_Ntac - w24_Ntac,
  J_w36_w48    = w48_J    - w36_J, 
  Ntac_w36_w48 = w48_Ntac - w36_Ntac,
  J_w24_w48 = w48_J - w24_J, 
  Ntac_w24_w48 = w48_Ntac - w24_Ntac,
  levels = design_batchcorr
)

fit1_batchcorr <- lmFit(phos_F_renamed2_longterm_filt_norm_batchcorr, design_batchcorr)
fit2_batchcorr <- contrasts.fit(fit1_batchcorr, contrasts_batchcorr)
fit2_batchcorr <- eBayes(fit2_batchcorr)

colnames(fit2_batchcorr)


limma_results_F_longterm_main_w24_w36   <- get_limma_results(fit2_batchcorr, "main_w24_w36",   "F Main effect w24-36") # Total: 12 - UP: 7 | DOWN: 5
limma_results_F_longterm_main_w36_w48   <- get_limma_results(fit2_batchcorr, "Ntac_w36_w48",   "F Main effect w36-48") # Total: 0 - UP: 0 | DOWN: 0
limma_results_F_longterm_main_w24_w48   <- get_limma_results(fit2_batchcorr, "Ntac_w24_w48",   "F Main effect w24-48") # Total: 40 - UP: 25 | DOWN: 15

limma_results_F_longterm_J_w24_w36_batchcorr      <- get_limma_results(fit2_batchcorr, "J_w24_w36",      "F J w24-36")       # Total: 0 - UP: 0 | DOWN: 0
limma_results_F_longterm_Ntac_w24_w36_batchcorr   <- get_limma_results(fit2_batchcorr, "Ntac_w24_w36",   "F Ntac w24-36")    # Total: 2 - UP: 1 | DOWN: 1
limma_results_F_longterm_J_w36_w48_batchcorr      <- get_limma_results(fit2_batchcorr, "J_w36_w48",      "F J w36-48")       # Total: 2 - UP: 2 | DOWN: 0
limma_results_F_longterm_Ntac_w36_w48_batchcorr   <- get_limma_results(fit2_batchcorr, "Ntac_w36_w48",   "F Ntac w36-48")    # Total: 0 - UP: 0 | DOWN: 0
limma_results_F_longterm_J_w24_w48   <- get_limma_results(fit2_batchcorr, "J_w24_w48",   "F J w24-48") # Total: 18 - UP: 18 | DOWN: 10
limma_results_F_longterm_Ntac_w24_w48   <- get_limma_results(fit2_batchcorr, "Ntac_w24_w48",   "F Ntac w24-48") # Total: 48 - UP: 30 | DOWN: 18

```
# Limma: non-batchcorr data
```{r}
# Limma: non-batchcorr data (batch modeled in design) — FEMALE
class(metadata_F_longterm$weeks)
levels(metadata_F_longterm$weeks)

metadata_F_longterm$weeks  <- factor(metadata_F_longterm$weeks,  levels = c("24","36","48"))
metadata_F_longterm$strain <- factor(metadata_F_longterm$strain, levels = c("J","Ntac"))
metadata_F_longterm$Combined <-
  with(metadata_F_longterm, factor(paste0("w", weeks, "_", strain)))

class(metadata_F_longterm$Combined)
levels(metadata_F_longterm$Combined)

# Design includes batch
design <- model.matrix(~0 + Combined + beatbox_batch, data = metadata_F_longterm)
colnames(design) <- sub("Combined", "", colnames(design))
colnames(design)

# Contrasts: main effects (avg over strains) + strain-specific
contrasts <- makeContrasts(
  main_w24_w36 = ((w36_J + w36_Ntac)/2) - ((w24_J + w24_Ntac)/2), 
  main_w36_w48 = ((w48_J + w36_Ntac)/2) - ((w48_J + w36_Ntac)/2),
  main_w24_w38 = ((w48_J + w24_Ntac)/2) - ((w48_J + w24_Ntac)/2),
  
  main_w24_w36 = ((w36_J + w36_Ntac)/2) - ((w24_J + w24_Ntac)/2), 
  main_w36_w48 = ((w48_J + w36_Ntac)/2) - ((w48_J + w36_Ntac)/2),
  main_w24_w38 = ((w48_J + w24_Ntac)/2) - ((w48_J + w24_Ntac)/2),
  
  J_w24_w36    = w36_J    - w24_J,
  Ntac_w24_w36 = w36_Ntac - w24_Ntac,
  J_w36_w48    = w48_J    - w36_J, 
  Ntac_w36_w48 = w48_Ntac - w36_Ntac,
  J_w24_w48 = w48_J - w24_J, 
  Ntac_w24_w48 = w48_Ntac - w24_Ntac,
  
  levels = design
)

# Use the NON-batch-corrected expression (batch handled in design)
fit1 <- lmFit(phos_F_renamed2_longterm_filt_norm, design)
fit2 <- contrasts.fit(fit1, contrasts)
fit2 <- eBayes(fit2)

colnames(fit2)


limma_results_F_longterm_main_w24_w36   <- get_limma_results(fit2, "main_w24_w36",   "F Main effect w24-36") # Total: 404 - UP: 133 | DOWN: 271
limma_results_F_longterm_main_w36_w48   <- get_limma_results(fit2, "Ntac_w36_w48",   "F Main effect w36-48") # Total: 0 - UP: 0 | DOWN: 0
limma_results_F_longterm_main_w24_w48   <- get_limma_results(fit2, "Ntac_w24_w48",   "F Main effect w24-48") # Total: 40 - UP: 25 | DOWN: 15

limma_results_F_longterm_J_w24_w36   <- get_limma_results(fit2, "J_w24_w36",   "F J w24-36") # Total: 4 - UP: 2 | DOWN: 2
limma_results_F_longterm_Ntac_w24_w36   <- get_limma_results(fit2, "Ntac_w24_w36",   "F Ntac w24-36") # Total: 7 - UP: 3 | DOWN: 4

limma_results_F_longterm_J_w36_w48   <- get_limma_results(fit2, "J_w36_w48",   "F J w36-48") # Total: 2 - UP: 2 | DOWN: 0
limma_results_F_longterm_Ntac_w36_w48   <- get_limma_results(fit2, "Ntac_w36_w48",   "F Ntac w36-48") # Total: 0 - UP: 0 | DOWN: 0

limma_results_F_longterm_J_w24_w48   <- get_limma_results(fit2, "J_w24_w48",   "F J w24-48") # Total: 3 - UP: 2 | DOWN: 1
limma_results_F_longterm_Ntac_w24_w48   <- get_limma_results(fit2, "Ntac_w24_w48",   "F Ntac w24-48") # Total: 40 - UP: 25 | DOWN: 15

```

