---
title: "female_prot_limma"
format: html
---


# Load dependencies
```{r setup}
#| message: false
#| warning: false

source(here::here("R/library.R"))
load(here::here("data/metadata_F_filtered.rda"))
load(here::here("data/prot_female_removeoutlier_filt_median.rda"))
load(here::here("data/prot_female_removeoutlier_filt_median_batchcorr.rda"))
```


# Subrgoup male week12
```{r}
metadata_F12 <- metadata_F_filtered %>% dplyr::filter(weeks == "12")
df_F12_batchcorr <- prot_female_removeoutlier_filt_median_batchcorr[, metadata_F12$new_sample_id] # 7641

dim(df_F12_batchcorr) # 35 samples
all(colnames(df_F12_batchcorr) == metadata_F12$new_sample_id)  # Should be TRUE
```
# Correlation
```{r}
mat <- as.matrix(df_F12)
cor_matrix <- cor(mat, method = "pearson", use = "pairwise.complete.obs")

# 2) Annotations
annotation_col <- data.frame(
  Diet   = metadata_F12$diet,
  Strain = metadata_F12$strain,
  row.names = metadata_F12$new_sample_id
)

annotation_colors <- list(
  Diet   = c(LFD = "#21908CFF", FFMD = "#D55E00"),
  Strain = c(J = "#CCBB44", Ntac = "#AA3377")
)

F12_heatmap_corr <- pheatmap(
  cor_matrix,
  color = colorRampPalette(c("lightpink", "white", "lightskyblue3"))(100),
  main = "Pearson Correlation Heatmap Female 12week",
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  show_rownames = TRUE,
  show_colnames = TRUE,
  scale = "none",
  annotation_col = annotation_col,
  annotation_colors = annotation_colors,
  breaks = seq(0.7, 1, length.out = 100)
)

cor_values  <- cor_matrix[upper.tri(cor_matrix)]
min_corr    <- min(cor_values)
max_corr    <- max(cor_values)
median_corr <- median(cor_values)
mean_corr   <- mean(cor_values)

cat("Minimum correlation:", round(min_corr, 3), "\n")
cat("Maximum correlation:", round(max_corr, 3), "\n")
cat("Median correlation:",  round(median_corr, 3), "\n")
cat("Mean correlation:",    round(mean_corr, 3), "\n")

ggsave(file.path("doc", "F12_heatmap_corr.png"), plot = F12_heatmap_corr, width = 10, height = 7, dpi = 300, bg = "white")
```

# PCA
```{r}
n_original <- nrow(df_F12) # 7422
df_nona <- na.omit(df_F12) # 6586
n_nona <- nrow(df_nona)

# transpose data 
pca_nona <- prcomp(t(df_nona), scale = TRUE)
# quick scatter plot
factoextra::fviz_pca_ind(pca_nona) 
plot(pca_nona$x[,1], pca_nona$x[,2])

# Eigenvalues (variance explained by each PC)
pca_var <- pca_nona$sdev^2 
pca_var_perc <- round(pca_var/sum(pca_var)*100, digits = 1)
fviz_eig(pca_nona, addlabels = TRUE)  # scree plot 

pca_results <- as.data.frame(pca_nona$x) %>%
  tibble::rownames_to_column("new_sample_id")  # keep sample IDs

pca_data <- pca_results %>%
  dplyr::select(new_sample_id, PC1, PC2, PC3, PC4) %>% 
  dplyr::inner_join(metadata_F12, by = "new_sample_id") %>%
  dplyr::mutate(
    hover_text = paste0(
      "Sample: ", sample_id,
      "<br>New_Sample: ", new_sample_id,
      "<br>Diet: ", diet,
      "<br>Strain: ", strain
    )
  )

# Should be all TRUE / empty set
all(pca_results$new_sample_id %in% metadata_F12$new_sample_id)

pca_diet12 <- plot_pca(
    data = pca_data,
    color_var = "diet",
    shape_var = "strain",
    color_vals = c("LFD" = "#21908CFF", "FFMD" = "#D55E00"),
    plot_title = "Global, F, 12week (n=35)",
    ellipse = TRUE
)

pca_strain12 <- plot_pca(
    data = pca_data,
    color_var = "strain",
    shape_var = "diet",
    color_vals = c("Ntac" = "#AA3377", "J" = "#CCBB44"),
    plot_title = "Global, F, 12week (n=35)",
    ellipse = TRUE
)


plotly::ggplotly(pca_strain12)
ggsave(file.path("doc", "pca_strain12.png"), plot = pca_strain12, width = 7, height = 5, dpi = 300, bg = "white")

```


# Limma (use batchcorr data)
```{r}
metadata_F12 <- metadata_F12 %>%
  dplyr::mutate(
    diet   = factor(diet, levels = c("LFD", "FFMD")),
    strain = factor(strain, levels = c("J", "Ntac"))
  )

levels(metadata_F12$diet)
levels(metadata_F12$strain)

table(metadata_F12$diet)   # LFD-12, FFMD-23
table(metadata_F12$strain) # J-17, Ntac-18

# create design matrix
design_matrix <- model.matrix(~ diet + strain, data = metadata_F12)
colnames(design_matrix)
fit  <- limma::lmFit(df_F12_batchcorr, design_matrix)
fit2 <- limma::eBayes(fit)

# use get_limma_results function
limma_results_F12_diet_batchcorr   <- get_limma_results(fit2, "dietFFMD",   "F12: Diet") # Total: 1357 - UP: 677 | DOWN: 680
limma_results_F12_strain_batchcorr <- get_limma_results(fit2, "strainNtac", "F12: Strain") # Total 37 - UP: 18 | DOWN: 19

# Diet histogram
hist(limma_results_F12_diet_batchcorr$top_table$P.Value,   main = "F12: Diet main effect (batchcorr)",   xlab = "P-value", col = "darkslategray4", breaks = 30)
hist(limma_results_F12_strain_batchcorr$top_table$P.Value, main = "F12: Strain main effect (batchcorr)", xlab = "P-value", col = "darkslategray4", breaks = 30)

png(file.path("doc", "F12_main_diet_hist_batchcorr.png"), width = 5, height = 4, units = "in", res = 300, bg = "white")
hist(limma_results_F12_diet_batchcorr   <- get_limma_results(fit2, "dietFFMD",   "F12: Diet") # Total: 1164 - UP: 588 | DOWN: 576
$top_table$P.Value, main = "F12: Diet main effect (batchcorr)", xlab = "P-value", col = "darkslategray4", breaks = 30)
dev.off()

png(file.path("doc", "F12_main_strain_hist_batchcorr.png"), width = 5, height = 4, units = "in", res = 300, bg = "white")
hist(limma_results_F12_strain_batchcorr$top_table$P.Value, main = "F12: Strain main effect (batchcorr)", xlab = "P-value", col = "darkslategray4", breaks = 30)
dev.off()

```

# Limma use non-batchcorr data
```{r}
df_F12 <- prot_female_removeoutlier_filt_median[, metadata_F12$new_sample_id] # 7641

dim(df_F12) # 35 samples
all(colnames(df_F12) == metadata_F12$new_sample_id)  # Should be TRUE

# create design matrix
design_matrix <- model.matrix(~ diet + strain + beatbox_batch, data = metadata_F12)
colnames(design_matrix)
fit  <- limma::lmFit(df_F12, design_matrix)
fit2 <- limma::eBayes(fit)

# use get_limma_results function
limma_results_F12_diet   <- get_limma_results(fit2, "dietFFMD",   "F12: Diet") # Total: 1164 - UP: 588 | DOWN: 576
limma_results_F12_strain <- get_limma_results(fit2, "strainNtac", "F12: Strain") # Total 27 - UP: 13 | DOWN: 14

# Diet histogram
hist(limma_results_F12_diet$top_table$P.Value,   main = "F12: Diet main effect",   xlab = "P-value", col = "darkslategray4", breaks = 30)
hist(limma_results_F12_strain$top_table$P.Value, main = "F12: Strain main effect", xlab = "P-value", col = "darkslategray4", breaks = 30)

png(file.path("doc", "F12_main_diet_hist.png"), width = 5, height = 4, units = "in", res = 300, bg = "white")
hist(limma_results_F12_diet$top_table$P.Value, main = "F12: Diet main effect", xlab = "P-value", col = "darkslategray4", breaks = 30)
dev.off()

png(file.path("doc", "F12_main_strain_hist.png"), width = 5, height = 4, units = "in", res = 300, bg = "white")
hist(limma_results_F12_strain$top_table$P.Value, main = "F12: Strain main effect", xlab = "P-value", col = "darkslategray4", breaks = 30)
dev.off()

```


