library(usethis)
library(readr)
library(readxl)
library(dplyr)
library(stringr)
library(tibble)
library(matrixStats)
library(tidyverse)  # For data manipulation (dplyr, ggplot2, etc.)
library(here)       # For portable file paths
library(dplyr)
library(matrixStats)
library(ggplot2)
library(ggrepel)   # for better label placement


library(dplyr)
library(readxl)
library(PhosR)
library(limma)
library(writexl)
library(svglite)
library(factoextra)
library(matrixStats)
library(reshape2)
library(pheatmap)
library(openxlsx)
library(writexl)
library(clusterProfiler) # core GSEA and enrichment functions
library(org.Mm.eg.db) # gene annotation database (here mouse SYMBOL→Entrez)
library(ggrepel)
library(ggplot2)
library(dendextend)
library(tibble)
library(cluster)
library(enrichplot)
library(eulerr)
library(VennDiagram)
library(ggpubr)
library(UpSetR)
library(ppcor)
library(ComplexUpset)
library(Rdpack)
library(devtools)
library(factoextra)
library(readr)
library(here)
library(purrr)
library(visdat)
library(stringr)
library(RColorBrewer)

library(SummarizedExperiment)
library(PhosR)           # for PhosphoExperiment (if available)
library(limma)           # for removeBatchEffect
library(edgeR)
library(pheatmap)
library(viridis)
library(patchwork)
